CREATE TABLE IF NOT EXISTS files (
  id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
  file_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(64) NOT NULL,
  content VARCHAR(32) NOT NULL,
  hash VARCHAR(64) NOT NULL,
  bucket VARCHAR(32) NOT NULL
)
