CREATE TABLE IF NOT EXISTS files (
  id VARCHAR(40) NOT NULL PRIMARY KEY,
  file_id VARCHAR(40) NOT NULL,
  name VARCHAR(64) NOT NULL,
  content_type VARCHAR(32) NOT NULL,
  hash VARCHAR(64) NOT NULL,
  bucket VARCHAR(32) NOT NULL,
  spoiler BOOLEAN NOT NULL DEFAULT FALSE,
  width INTEGER UNSIGNED,
  height INTEGER UNSIGNED
)
